# Generated by Django 5.2.17 on 2026-10-03 22:29

import apps.github.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(help_text='usuario/repositorio', max_length=200, verbose_name='repositorio')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='rama')),
                ('folder', models.CharField(blank=True, help_text='p. ej. metodos-numericos/clases; vacío = raíz del repositorio', max_length=300, verbose_name='carpeta')),
                ('webhook_secret', models.CharField(default=apps.github.models.new_webhook_secret, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('skipped', models.JSONField(blank=True, default=dict)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.TextField()),
                ('login', models.CharField(max_length=100)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
