# Generated by Django 5.2.17 on 2026-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English')], max_length=8, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='zona horaria'),
        ),
    ]
