# Generated by Django 5.2.17 on 2026-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_language_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'Automático (como el sistema)'), ('light', 'Claro'), ('dark', 'Oscuro')], default='', max_length=8, verbose_name='tema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('guest', 'Invitado')], default='student', max_length=10, verbose_name='rol'),
        ),
    ]
