# Generated by Django 5.2.17 on 2026-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
