# Generated by Django 5.2.17 on 2026-09-28 17:25

import apps.live.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('source', models.TextField(verbose_name='fuente YAML')),
                ('compiled', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='courses.course')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slides', models.JSONField()),
                ('pin', models.CharField(default=apps.live.models.new_pin, max_length=6)),
                ('status', models.CharField(choices=[('lobby', 'Sala de espera'), ('live', 'En curso'), ('ended', 'Terminada')], default='lobby', max_length=10)),
                ('index', models.PositiveIntegerField(default=0)),
                ('phase', models.CharField(choices=[('content', 'Contenido'), ('ready', 'Pregunta lista'), ('open', 'Respondiendo'), ('closed', 'Cerrada'), ('results', 'Resultados')], default='content', max_length=10)),
                ('opened', models.JSONField(default=list)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('answers_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='live.deck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_index', models.PositiveIntegerField()),
                ('item_id', models.CharField(max_length=120)),
                ('item_version', models.CharField(max_length=32)),
                ('answer', models.JSONField()),
                ('correct', models.BooleanField()),
                ('fraction', models.FloatField()),
                ('points', models.FloatField()),
                ('elapsed_ms', models.PositiveIntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='live.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ended'), _negated=True), fields=('pin',), name='unique_pin_among_active'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ended'), _negated=True), fields=('course',), name='one_active_session_per_course'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='one_participant_row'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('session', 'slide_index', 'student'), name='one_answer_per_question'),
        ),
    ]
