# Generated by Django 5.2.17 on 2026-10-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_dismissed'),
        ('live', '0002_guests_and_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='paused_remaining_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('lobby', 'Sala de espera'), ('live', 'En curso'), ('paused', 'En pausa'), ('ended', 'Terminada')], default='lobby', max_length=10),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='live.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collapsed', models.BooleanField(default=False)),
                ('github_folder', models.CharField(blank=True, max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='live.section'),
        ),
    ]
