# Generated by Django 5.2.18 on 2026-10-07 16:42

from django.db import migrations, models


def fill_scores(apps, schema_editor):
    """Las respuestas anteriores no tenían bono por rapidez: sus puntos de juego son 1000 × puntos."""
    Response = apps.get_model("live", "Response")
    for response in Response.objects.all().only("pk", "points"):
        Response.objects.filter(pk=response.pk).update(score=round(1000 * response.points))


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_recompile_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='speed_bonus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(fill_scores, migrations.RunPython.noop),
    ]
