# Generated by Django 5.2.18 on 2026-10-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def keep_automatic(apps, schema_editor):
    """Las respuestas anteriores no tienen corrección manual: lo automático es lo que cuenta."""
    Response = apps.get_model("live", "Response")
    Response.objects.update(auto_points=F("points"), auto_correct=F("correct"))


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_speed_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='auto_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='auto_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(keep_automatic, migrations.RunPython.noop),
    ]
